# Generated by Django 5.1.1 on 2024-09-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_appointment_guest_email_appointment_guest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='guest_name',
        ),
    ]
